export type QueryType = "traversal" | "aggregation" | "path_finding" | "neighbors";

export type ResponseFormat = "raw" | "llm";

export interface OrbitNodeSelector {
  id: string;
  entity: string;
  columns?: string[];
  filters?: Record<string, unknown>;
  node_ids?: number[];
}

export interface OrbitRelationship {
  type: string;
  from: string;
  to: string;
}

export interface OrbitAggregation {
  function: "count" | "sum" | "avg" | "min" | "max";
  target: string;
  alias: string;
  column?: string;
}

export interface OrbitGroupBy {
  kind: "node";
  node: string;
}

export interface OrbitPathConfig {
  type: "shortest" | "all";
  from: string;
  to: string;
  max_depth: number;
  rel_types?: string[];
}

export interface OrbitNeighborsConfig {
  node: string;
  direction: "incoming" | "outgoing" | "both";
  rel_types?: string[];
  node_types?: string[];
}

export interface OrbitQuery {
  query_type: QueryType;
  node?: OrbitNodeSelector;
  nodes?: OrbitNodeSelector[];
  from?: OrbitNodeSelector;
  to?: OrbitNodeSelector;
  max_path_length?: number;
  relationships?: OrbitRelationship[];
  aggregations?: OrbitAggregation[];
  group_by?: OrbitGroupBy[];
  path?: OrbitPathConfig;
  neighbors?: OrbitNodeSelector | OrbitNeighborsConfig;
  limit?: number;
  order_by?: { column: string; direction: "ASC" | "DESC" };
  aggregation_sort?: { column: string; direction: "ASC" | "DESC" };
  options?: { dynamic_columns?: string };
}

export interface OrbitQueryEnvelope {
  query: OrbitQuery;
  format?: ResponseFormat;
}

export interface OrbitQueryResult {
  result: {
    format_version: string;
    query_type: QueryType;
    nodes: unknown[];
    edges: unknown[];
    group_columns?: unknown[];
    columns?: unknown[];
    rows?: unknown[];
  };
  query_type: QueryType;
  raw_query_strings: string[] | null;
  row_count: number;
}

export interface DigitalTwinNode {
  id: string;
  type: string;
  label: string;
  properties: Record<string, unknown>;
  riskScore?: number;
}

export interface DigitalTwinEdge {
  source: string;
  target: string;
  type: string;
  weight?: number;
  metadata?: Record<string, unknown>;
}

export interface QueryTiming {
  queryType: string;
  queryName: string;
  durationMs: number;
  nodeCount: number;
  edgeCount: number;
  status: "success" | "error";
}

export interface DigitalTwin {
  nodes: DigitalTwinNode[];
  edges: DigitalTwinEdge[];
  metadata: {
    projectPath: string;
    mrIid?: number;
    branch?: string;
    timestamp: string;
    queryTimings?: QueryTiming[];
  };
}

export interface ChangeSimulation {
  changeDescription: string;
  changeScope: string[];
  blastRadius: {
    files: DigitalTwinNode[];
    services: DigitalTwinNode[];
    deployments: DigitalTwinNode[];
    pipelines: DigitalTwinNode[];
  };
  failurePredictions: FailurePrediction[];
  riskScore: number;
  riskLevel: "low" | "medium" | "high" | "critical";
}

export interface FailurePrediction {
  mode: string;
  probability: number;
  severity: "low" | "medium" | "high" | "critical";
  affectedComponent: string;
  description: string;
  historicalPrecedent?: HistoricalMatch;
}

export interface HistoricalMatch {
  mrIid: number;
  mrTitle: string;
  similarity: number;
  outcome: string;
  incidentId?: number;
  timestamp: string;
}

export interface MemoryRecord {
  mrIid: number;
  mrTitle: string;
  mrAuthor: string;
  filesChanged: string[];
  labels: string[];
  outcome: "success" | "rollback" | "incident" | "fix_required";
  incidentId?: number;
  description: string;
  rollbackReason?: string;
  timestamp: string;
}

export interface ReviewerRecommendation {
  username: string;
  expertise: string[];
  relevanceScore: number;
  currentWorkload: number;
}

export interface RollbackPlan {
  strategy: "revert" | "revert_and_fix" | "feature_flag" | "gradual_rollback";
  steps: string[];
  estimatedTime: string;
  riskLevel: "low" | "medium" | "high";
}

export interface TestPlan {
  unitTests: string[];
  integrationTests: string[];
  e2eTests: string[];
  suggestedFramework: string;
  coverageTargets: string[];
  recommendedTests?: string[];
}

export interface RemediationSuggestion {
  type: "fix_mr" | "config_change" | "rollback" | "feature_flag" | "test_addition";
  description: string;
  impact?: "critical" | "high" | "medium" | "low";
  autoGeneratedMr?: boolean;
  mrUrl?: string;
}

export interface SentinelReport {
  mrIid: number;
  mrTitle: string;
  digitalTwin: DigitalTwin;
  simulation: ChangeSimulation;
  historicalMatches: HistoricalMatch[];
  reviewerRecommendations: ReviewerRecommendation[];
  rollbackPlan: RollbackPlan;
  testPlan: TestPlan;
  remediations: RemediationSuggestion[];
  generatedAt: string;
}
