import type { RemediationSuggestion, FailurePrediction } from "../types.js";

export class RemediationPlanner {
  prioritize(predictions: FailurePrediction[]): RemediationSuggestion[] {
    const suggestions: RemediationSuggestion[] = [];

    const criticalPredictions = predictions.filter(
      (p) => p.severity === "critical",
    );
    for (const pred of criticalPredictions) {
      suggestions.push({
        type: "feature_flag",
        description: `Wrap ${pred.affectedComponent} changes behind a feature flag. Critical failure probability: ${(pred.probability * 100).toFixed(0)}%.`,
      });
    }

    const highVolumePredictions = predictions.filter(
      (p) => p.probability > 0.5 && p.severity !== "low",
    );
    for (const pred of highVolumePredictions) {
      suggestions.push({
        type: "fix_mr",
        description: `Preemptive fix for ${pred.affectedComponent}: ${pred.mode} detected with ${(pred.probability * 100).toFixed(0)}% probability.`,
      });
    }

    const affectedSystems = new Set(
      predictions.map((p) => p.affectedComponent),
    );
    if (affectedSystems.size > 3) {
      suggestions.push({
        type: "config_change",
        description: `Change touches ${affectedSystems.size} systems. Consider splitting into multiple smaller MRs for isolated rollout.`,
      });
    }

    suggestions.push({
      type: "test_addition",
      description: `Add regression tests covering ${predictions.map((p) => p.mode).join(", ")} scenarios.`,
    });

    return suggestions;
  }

  generateAutoFixMr(
    description: string,
    changedFiles: string[],
  ): RemediationSuggestion {
    return {
      type: "fix_mr",
      description: `Auto-generated fix: ${description}`,
      autoGeneratedMr: true,
    };
  }
}

export const remediationPlanner = new RemediationPlanner();
