import { describe, it, expect } from "vitest";
import { RemediationPlanner } from "../src/remediation/planner.js";
import type { FailurePrediction } from "../src/types.js";

describe("RemediationPlanner", () => {
  const planner = new RemediationPlanner();

  it("generates feature flag remediation for critical predictions", () => {
    const predictions: FailurePrediction[] = [
      { mode: "pipeline_failure", probability: 0.9, severity: "critical", affectedComponent: "auth-service", description: "" },
    ];
    const suggestions = planner.prioritize(predictions);
    expect(suggestions.some(s => s.type === "feature_flag")).toBe(true);
  });

  it("generates fix_mr for high probability predictions", () => {
    const predictions: FailurePrediction[] = [
      { mode: "downstream_breakage", probability: 0.8, severity: "high", affectedComponent: "api-gateway", description: "" },
    ];
    const suggestions = planner.prioritize(predictions);
    expect(suggestions.some(s => s.type === "fix_mr")).toBe(true);
  });

  it("always adds test_addition suggestion", () => {
    const suggestions = planner.prioritize([]);
    expect(suggestions.some(s => s.type === "test_addition")).toBe(true);
  });

  it("suggests split MR for many affected systems", () => {
    const predictions: FailurePrediction[] = [
      { mode: "failure", probability: 0.5, severity: "medium", affectedComponent: "sys1", description: "" },
      { mode: "failure", probability: 0.5, severity: "medium", affectedComponent: "sys2", description: "" },
      { mode: "failure", probability: 0.5, severity: "medium", affectedComponent: "sys3", description: "" },
      { mode: "failure", probability: 0.5, severity: "medium", affectedComponent: "sys4", description: "" },
    ];
    const suggestions = planner.prioritize(predictions);
    expect(suggestions.some(s => s.type === "config_change")).toBe(true);
  });

  it("generates auto-fix MR suggestion", () => {
    const fix = planner.generateAutoFixMr("Fix schema validation", ["flows/flow.yml"]);
    expect(fix.type).toBe("fix_mr");
    expect(fix.autoGeneratedMr).toBe(true);
    expect(fix.description).toContain("Fix schema validation");
  });
});
